-- Extend patients table with detailed demographic, residential, biometrics, and medical fields

ALTER TABLE patients
    ADD COLUMN IF NOT EXISTS sex_biological VARCHAR(20),
    ADD COLUMN IF NOT EXISTS gender_identity VARCHAR(50),
    ADD COLUMN IF NOT EXISTS marital_status VARCHAR(30),
    ADD COLUMN IF NOT EXISTS education_level VARCHAR(50),
    ADD COLUMN IF NOT EXISTS occupation VARCHAR(80),
    ADD COLUMN IF NOT EXISTS emergency_contact_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS emergency_contact_phone VARCHAR(40),
    ADD COLUMN IF NOT EXISTS city VARCHAR(80),
    ADD COLUMN IF NOT EXISTS municipality VARCHAR(80),
    ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(80),
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(15),
    ADD COLUMN IF NOT EXISTS housing_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS socioeconomic_stratum VARCHAR(10),
    ADD COLUMN IF NOT EXISTS residence_duration_months INTEGER,
    ADD COLUMN IF NOT EXISTS abdominal_circumference_cm NUMERIC(6,2),
    ADD COLUMN IF NOT EXISTS heart_rate_bpm INTEGER,
    ADD COLUMN IF NOT EXISTS respiratory_rate_rpm INTEGER,
    ADD COLUMN IF NOT EXISTS blood_pressure_sys INTEGER,
    ADD COLUMN IF NOT EXISTS blood_pressure_dia INTEGER,
    ADD COLUMN IF NOT EXISTS temperature_c NUMERIC(4,1),
    ADD COLUMN IF NOT EXISTS spo2 NUMERIC(5,2),
    ADD COLUMN IF NOT EXISTS allergies TEXT,
    ADD COLUMN IF NOT EXISTS medications TEXT,
    ADD COLUMN IF NOT EXISTS surgeries TEXT,
    ADD COLUMN IF NOT EXISTS family_history TEXT,
    ADD COLUMN IF NOT EXISTS habits TEXT,
    ADD COLUMN IF NOT EXISTS vaccines TEXT,
    ADD COLUMN IF NOT EXISTS chronic_conditions TEXT;
